# Generated by Django 5.2.7 on 2025-11-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=50)),
                ('linkedin', models.CharField(default='', max_length=50)),
                ('github', models.CharField(default='', max_length=50)),
                ('stackoverflow', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preamble_summary', models.TextField(blank=True, max_length=300000)),
                ('testimonial_carousel', models.TextField(blank=True, max_length=300000)),
                ('cms_samples', models.TextField(blank=True, max_length=300000)),
                ('book_lists', models.TextField(blank=True, max_length=300000)),
                ('udemy_courses_complete', models.TextField(blank=True, max_length=300000)),
                ('machine_learning_samples', models.TextField(blank=True, max_length=300000)),
                ('documentation_samples', models.TextField(blank=True, max_length=300000)),
                ('aTimeLogger', models.TextField(blank=True, max_length=300000)),
                ('further_research_forwards', models.TextField(blank=True, max_length=300000)),
            ],
        ),
    ]
