# Generated by Django 5.2.7 on 2025-11-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(blank=True, max_length=300000),
        ),
    ]
