# Generated by Django 5.2.7 on 2025-11-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacons', '0002_content_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='book_lists',
        ),
        migrations.RemoveField(
            model_name='content',
            name='testimonial_carousel',
        ),
        migrations.AddField(
            model_name='content',
            name='algorithms',
            field=models.TextField(blank=True, max_length=300000),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
