# Generated by Django 5.2.7 on 2025-11-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacons', '0003_remove_content_book_lists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='udemy_courses_complete',
        ),
        migrations.AddField(
            model_name='content',
            name='about',
            field=models.TextField(blank=True, max_length=300000),
        ),
    ]
